# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "xansar"
repo_name: "health-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 50

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/health-arxiv-daily.json'
json_gitpage_path: './docs/health-arxiv-daily-web.json'
json_wechat_path: './docs/health-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "HealthLLM": 
        filters: [
            "health LLM", 
            "medical LLM", 
            "clinical LLM"]
