title: HealthLLM Arxiv Daily
description: Automatically Update HealthLLM Papers Daily using Github Actions (Update Every 12th hours)
show_downloads: true

github:
  zip_url: https://github.com/xansar/health-arxiv-daily
  another_url: https://github.com/xansar/health-arxiv-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  twitter: AlphaRealcat
  github: xansar

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
